version: "3.3"
services:
  crawler:
    container_name: wakmusic-crawler
    image: wakmusic-crawler-v2:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./configs:/usr/src/app/configs
    environment:
      - TZ=Asia/Seoul
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "600MB"
